// Mocks generated by Mockito 5.4.6 from annotations
// in switch_app_freezed/test/utils/mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:flutter_riverpod/flutter_riverpod.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:switch_app_freezed/data/dto/switch_dto.dart' as _i7;
import 'package:switch_app_freezed/data/repository/switch_repository.dart'
    as _i6;
import 'package:switch_app_freezed/domain/logic/switch_notifier.dart' as _i4;
import 'package:switch_app_freezed/domain/models/switch_state.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeStreamNotifierProviderRef_0<T> extends _i1.SmartFake
    implements _i2.StreamNotifierProviderRef<T> {
  _FakeStreamNotifierProviderRef_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAsyncValue_1<T> extends _i1.SmartFake implements _i2.AsyncValue<T> {
  _FakeAsyncValue_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSwitchState_2 extends _i1.SmartFake implements _i3.SwitchState {
  _FakeSwitchState_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRef_3<State extends Object?> extends _i1.SmartFake
    implements _i2.Ref<State> {
  _FakeRef_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [SwitchNotifier].
///
/// See the documentation for Mockito's code generation for more information.
class MockSwitchNotifier extends _i1.Mock implements _i4.SwitchNotifier {
  MockSwitchNotifier() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.StreamNotifierProviderRef<_i3.SwitchState> get ref =>
      (super.noSuchMethod(
            Invocation.getter(#ref),
            returnValue: _FakeStreamNotifierProviderRef_0<_i3.SwitchState>(
              this,
              Invocation.getter(#ref),
            ),
          )
          as _i2.StreamNotifierProviderRef<_i3.SwitchState>);

  @override
  _i2.AsyncValue<_i3.SwitchState> get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _FakeAsyncValue_1<_i3.SwitchState>(
              this,
              Invocation.getter(#state),
            ),
          )
          as _i2.AsyncValue<_i3.SwitchState>);

  @override
  _i5.Future<_i3.SwitchState> get future =>
      (super.noSuchMethod(
            Invocation.getter(#future),
            returnValue: _i5.Future<_i3.SwitchState>.value(
              _FakeSwitchState_2(this, Invocation.getter(#future)),
            ),
          )
          as _i5.Future<_i3.SwitchState>);

  @override
  set state(_i2.AsyncValue<_i3.SwitchState>? newState) => super.noSuchMethod(
    Invocation.setter(#state, newState),
    returnValueForMissingStub: null,
  );

  @override
  _i5.Stream<_i3.SwitchState> build() =>
      (super.noSuchMethod(
            Invocation.method(#build, []),
            returnValue: _i5.Stream<_i3.SwitchState>.empty(),
          )
          as _i5.Stream<_i3.SwitchState>);

  @override
  _i5.Future<void> switchOn() =>
      (super.noSuchMethod(
            Invocation.method(#switchOn, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> switchOff() =>
      (super.noSuchMethod(
            Invocation.method(#switchOff, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  void listenSelf(
    void Function(
      _i2.AsyncValue<_i3.SwitchState>?,
      _i2.AsyncValue<_i3.SwitchState>,
    )?
    listener, {
    void Function(Object, StackTrace)? onError,
  }) => super.noSuchMethod(
    Invocation.method(#listenSelf, [listener], {#onError: onError}),
    returnValueForMissingStub: null,
  );

  @override
  _i5.Future<_i3.SwitchState> update(
    _i5.FutureOr<_i3.SwitchState> Function(_i3.SwitchState)? cb, {
    _i5.FutureOr<_i3.SwitchState> Function(Object, StackTrace)? onError,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#update, [cb], {#onError: onError}),
            returnValue: _i5.Future<_i3.SwitchState>.value(
              _FakeSwitchState_2(
                this,
                Invocation.method(#update, [cb], {#onError: onError}),
              ),
            ),
          )
          as _i5.Future<_i3.SwitchState>);

  @override
  bool updateShouldNotify(
    _i2.AsyncValue<_i3.SwitchState>? previous,
    _i2.AsyncValue<_i3.SwitchState>? next,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateShouldNotify, [previous, next]),
            returnValue: false,
          )
          as bool);
}

/// A class which mocks [SwitchRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockSwitchRepository extends _i1.Mock implements _i6.SwitchRepository {
  MockSwitchRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Ref<Object?> get ref =>
      (super.noSuchMethod(
            Invocation.getter(#ref),
            returnValue: _FakeRef_3<Object?>(this, Invocation.getter(#ref)),
          )
          as _i2.Ref<Object?>);

  @override
  _i5.Stream<_i7.SwitchDto> subscribeSwitchIsEnabled({
    required String? documentId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#subscribeSwitchIsEnabled, [], {
              #documentId: documentId,
            }),
            returnValue: _i5.Stream<_i7.SwitchDto>.empty(),
          )
          as _i5.Stream<_i7.SwitchDto>);

  @override
  _i5.Future<void> switchOn({required String? documentId}) =>
      (super.noSuchMethod(
            Invocation.method(#switchOn, [], {#documentId: documentId}),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> switchOff({required String? documentId}) =>
      (super.noSuchMethod(
            Invocation.method(#switchOff, [], {#documentId: documentId}),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}
